site_name: Mongoose Server
site_description: High-performance, event-driven server framework
site_url: https://gregv12.github.io/fluxtion-server/
repo_url: https://github.com/gregv12/fluxtion-server
repo_name: gregv12/fluxtion-server
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.sections
    - content.code.copy
    - content.action.edit
    - content.tabs.link
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: blue
      accent: indigo

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.critic
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - attr_list
  - tables

plugins:
  - search
  - mermaid2
  - awesome-pages

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/gregv12

nav:
  - Home: index.md
  - Guide:
      - Overview: guide/overview.md
      - Examples:
          - Fluent API: guide/file-and-memory-feeds-example.md
          - YAML config: guide/file-and-memory-feeds-yaml-example.md
      - Plugins:
          - Event sink plugin: guide/writing-a-message-sink-plugin.md
          - Event source plugin: guide/writing-an-event-source-plugin.md
          - Service plugin: guide/writing-a-service-plugin.md
          - Publishing service plugin: guide/writing-a-publishing-service-plugin.md
          - Typed invoke publishing service plugin: guide/writing-a-typed-invoke-publishing-service-plugin.md
      - How-to:
          - Subscribe to named event feeds: guide/subscribing-to-named-event-feeds.md
          - Add an admin command: guide/writing-an-admin-command.md
          - Using the scheduler service: guide/using-the-scheduler-service.md
          - Write a custom EventToInvokeStrategy: guide/writing-a-custom-event-to-invoke-strategy.md
          - Core pin agent threads: guide/how-to-core-pin.md
          - Inject config into a processor: guide/injecting-config-into-a-processor.md

  - Architecture and design:
      - Doc description: architecture/architecture_index.md
      - Overview: architecture/overview.md
      - Event flow: architecture/event-flow.md
      - Sequence event subscription: architecture/sequence-diagrams/event-subscription.md
      - Sequence event processing: architecture/sequence-diagrams/event-processing.md
      - Threading model: guide/threading-model.md

